language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      curl https://bodoni.github.io/travis/update_documentation.sh | bash;
    fi

env:
  global:
    - secure: aPp9VH79bmQiwSw3yYmbJoSRV5XuJXXQRyZSxhr4+mNVSVnE2q8e3RuGk7/odcYhwsbFy9DxqlKZl+4n5yemO0NXkDtf+aTGn/rEVIyMHWz4lqP0L08H2GPlVZcTy50F31tWpVFXawlElHgFKix1l6AFd3I5uNed1OXLtsZPjCKBr/5WYRxUAd02Ag0tkvhWXl+RBP2f0qN7vpHVDENhDeE0D/5tQklQ56vx3q7BlYo8eqp4MDpfTf1l8bwdY3kH6JjJlGpftjJ0lHGEXQwYZsh8plYM1dpWGcax2H7VgpEfj+nuZA17aeApHc+BpAOCvCwRV7xQiV5ZA49Y1kvlAzZ+aVyjaMZyWJjP84qwjy6SRLIogll7vMmfbEFGkivIajsmxkcd1+8xqqlc5ItqpJigVZctfPd1SRO7ZngDJApR9BRvKmmy8WmWTVx5F+mPFnIZn6m00HIC9toy/kUUH5z89120JZaeZGwshb7A0lJQEXdX1Yt8Bov2QM9V2BVt18vr2HhL8nYk6SpXj5GIGTkKxCzsPtoH1qHx8CyQOqyIJGs4F3zhX8seUauJUxrC0L5Aifo6u/Z++K44HBt0Yb4O7MUe/zlcFMDz+61zNMQLYV9N7dW2PDmAu7+bg9VeNqkkZyKhY4aB0E+8Fa7f/vuGdIqeAZCoCWwXXAKx8lc=

notifications:
  email: false
