[package]
name = "curve"
version = "0.3.0"
license = "MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides curves."
documentation = "https://bodoni.github.io/curve"
homepage = "https://github.com/bodoni/curve"
repository = "https://github.com/bodoni/curve"

[dependencies]
num-traits = "0.1"
